superfaceai/docs

- docs/guides/publishing.md
- sidebars.js
First minimal attempt covering only the necessary steps.
Preview: https://pr-35-superface-docs.vercel.app/docs/guides/publishing
> feat(guides): Publishing capabilities, vol. 1

- package.json
- yarn.lock
With exception of remark-deflist which was converted to ESM and breaks the build.
> chore(deps): Update dependencies

- .github/workflows/prune-closed-pr-deployments.yml
> Revert "chore(ci/cd): Remove workflow for pruning PR previews"

- docs/support.mdx
- docusaurus.config.js
This adds landing page with ways how to reach us.
Kickoff taking https://www.notion.so/superface/Contacts-1c3d503924a846e1b75ef9e8167bb22c, lets discuss what should and what shouldn't be there.
> Support page

- docs/guides/api-keys.md
- sidebars.js
This is ready for prelimnary review:
> feat(guide): Add Setting provider API keys

- docs/reference/reference-intro.mdx
Fixing rendering of spaces in Reference index. See [Slack](https://superfaceai.slack.com/archives/C029GG1DQSK/p1632474880006600).
> chore: Fixed row spacing in Reference index

- docs/comlink/reference/map.mdx
Add a section about path parameters to map reference
> feat: Add Path Parameters to map ref

- docusaurus.config.js
- Use "Superface" in alts for logos
- Use relative links for assets
> chore(config): Minor config improvements

- package.json
- yarn.lock
Blocked on https://github.com/facebook/docusaurus/issues/5863
> chore(dependencies): Update dependencies

- docs/guides/map-capability-to-provider.md
> fix(map-capability): Remove @version in create

- docs/reference/glossary.md
- docs/reference/one-sdk.mdx
- sidebars.js
(Ignore the commit messages, it will be all squashed :foot:)
Rendered page: https://pr-79-superface-docs.vercel.app/docs/reference/glossary
> feat: Add glossary

- .github/algolia/config.json
- .github/workflows/ci-cd-pipeline.yml
- docusaurus.config.js
- package.json
- yarn.lock
- Add Algolia configuration to Docusaurus config
- Add indexing to CI/CD pipeline
> Enable search and add indexing with Algolia

- docs/comlink/reference/binary_data.mdx
- sidebars.js
This PR takes documentation on PR introducing `BinaryData`to our documentation.
I struggled where to add it, so any suggestion is welcome.
> BinaryData docs

- docs/guides/add-new-provider.md
- docs/guides/create-new-use-case.md
- docs/guides/map-use-case-to-provider.md
This PR updates create new use case guide with use of prepare command.
Goal is to update files describing Profile, Provider and Map creation.
> chore: use prepare instead of create

- docs/api-examples/slack.mdx
Insalling should be corrected to installing
> fix: Fix typo "insalling"

- docs/examples/index.mdx
- docs/faq.mdx
- docs/index.mdx
- docs/migrate.mdx
- docusaurus.config.js
- sidebars.js
Adding an index for the SDKs to they are visible on one page. Also updated FAQ and adding correct link to the migrate page.
> chore: Add SDK examples index and update FAQ

- docs/faq.mdx
- docs/introduction/getting-started.mdx
- docs/introduction/quick-start.mdx
Adding:
- Profile ID information to the CLI quick start
- Python version information at the top of the 5 min quick start
> Update: Add info about profile ID control

- docs/api-examples/hubspot.mdx
- docs/api-examples/infobip.mdx
- docs/api-examples/lob.mdx
- docs/api-examples/notion.mdx
- docs/api-examples/pagerduty.mdx
- docs/api-examples/pipedrive.mdx
- docs/api-examples/resend.mdx
- docs/api-examples/slack.mdx
- docs/faq.mdx
- docs/guides/debugging-onesdk.mdx
- docs/guides/setup-the-environment.md
- docs/introduction/getting-started.mdx
- docs/introduction/quick-start.mdx
Updates:
- Quick Starts and the provider examples to include a more explicit call out for installing via NPM on Windows
- Adds FAQ question about installing on Windows
> chore: update to make non homebrew install clearer

- src/css/custom.css
- Update the CSS to remove the underlined links on the index pages
> chore: update css

- docs/tools/jira.mdx
- docs/tools/notion.mdx
- Adding Loom walkthroughs for Notion and Jira
> chore: add the loom walkthroughs

- docs/agent/index.mdx
Fixing url to correctly access Get Demo form.
> fix: get-demo url

- docs/tools/create-tools.mdx
Adds:
- Video overviews for the initial steps of authoring a tool in Superface
> update: add video overviews to the steps for authoring

- docs/api/examples/anthropic.mdx
- static/notebooks/superface_hub_api_anthropic_weather_example.ipynb
- Changes demo references for Anthropic user id
> update: demo user id reference

- docs/agent/custom-instructions.mdx
- docs/agent/example-videos.mdx
- docs/agent/index.mdx
- sidebars.js
Adds:
- Overview video on AI Agent index
- Video to Custom Intructions page
- New example videos page
- Google sheets -> Pipedrive recipe walkthrough video
> Add videos
