superfaceai/docs

docusaurus.config.js, src/css/custom.css, static/crisp.js
This PR adds [Crisp Chat](https://crisp.chat/en/) bubble to the Docs to continue the support experience from the main website.
---
The configuration fetches `CRISP_WEBSITE_ID` from env at build time and renders the following at every page:
```html
<script src="./crisp.js" crisp-website-id="4686a....." defer></script>
```
`crisp.js` then reads the website id from the `script` and sets up Crisp using their provided snippet.
=> feat: Adding Crisp to the site

.github/workflows/prune-closed-pr-deployments.yml
It turns out we actually need to run this, but since the repo is public, the workflow runs using a different access scope so we’re just removing the deployments from the environment.
=> chore: Pruning branches only removes deployments

docs/guides/run-capability.md
This PR fixes the wrong [CLI command shown in the doc](https://pr-46-superface-docs.vercel.app/docs/guides/run-capability#cli-configuration) on how to run the authored capability locally.
=> fix: CLI command for configuring local provider

docs/guides/add-new-provider.md
This PR fixes link in `Add new provider` guide. `google-apis` has been renamed to `google-apis-maps`.
=> Fix link to provider using API key in request query

docs/guides/create-new-capability.md, docusaurus.config.js, package.json, yarn.lock
remark-deflist migrated to ES modules which is issue for backwards compatibility, but the package is otherwise quite unmaintained.
Deflists have only limited use in the current docs and present non-standard syntax. Let's just use bullet lists even if it's less semantically correct.
=> chore: Remove remark-deflist

docs/getting-started.mdx, docs/guides/setup-the-environment.md, docs/reference/one-sdk.mdx, docs/reference/reference-intro.mdx
This is to accommodate for stuff removed from OneSDK readme: https://github.com/superfaceai/one-sdk-js/tree/aafe33692021d046f2cf248377bc79541a546095#handling-the-results-from-perform
=> feat: Add OneSDK reference

sidebars.js
When opening [Add new provider](https://superface.ai/docs/guides/add-new-provider) guide, the sidebar switches non-authoring sidebar.
That sidebar is important to provide backward-continuity from [Find provider by name](https://superface.ai/docs/guides/find-provider-by-name) that is linked from the former guide, however it should only render on this specific page.
Fixes #68 
cc @SuperVrata
=> fix: “Add new provider ” keeps correct sidebar

docs/comlink/reference/map.mdx, docs/guides/map-capability-to-provider.md, docs/guides/test-capability.md
- Comlink map examples were pointing to the `/capabilities/` directory; replaced with commit permalink
- I noticed a few links pointing to Comlink spec as "reference"
Thanks to @tmladek for heads up!
=> fix: Invalid links, reference / spec

docs/index.md
During testing with users happened that they didn't install OneSDK package. So I added it in fast track steps. 
Also linked terms as use-case, profile and provider to glossary.
=> Explicitly mention to install OneSDK in fast track

.github/workflows/ci-cd-pipeline.yml, src/css/custom.css
This PR fixes styling of highlighted code block in light and dark mode by changing custom.css according to Docusaurus documentation: https://docusaurus.io/docs/markdown-features/code-blocks#line-highlighting.
Light mode before fix:
Light mode after fix:
Dark mode before fix:
Dark mode after fix:
=> Fix highlighted code block background color

docs/comlink/reference/map.mdx
Adding reference documentation for Operation behavior in Comlink Map.
**Preview**
https://pr-105-superface-docs.vercel.app/docs/comlink/reference/map#operation
Proposed ToC:
- Operation
- Defining operation
- Accessing arguments
- Return & Fail
- Calling operation
- Calling in-place
- Calling with handler
- Operation caveats
=> feat(Comlink reference): Documenting Map operations

vercel.json
Adding redirects for old docs links so that they point into `classic/` subdocs.
=> chore: Add redirects for old links

docs/index.mdx, docs/reference/superjson.mdx, docusaurus.config.js, sidebars.js
- corrects slug of new superjson reference
- renames index.md to index.mds and uses className over class
- uses absolute urls for cards on home
- fixes header link to classic docs
=> Fix navigation on home page

docs/api-examples/index.mdx, docs/index.mdx, sidebars.js, src/css/custom.css
Adds an index page for the API examples so that they can all be shown in one place rather than linking directly to HubSpot.
=> chore: add index for api examples

docs/introduction/install-superface.mdx, sidebars.js
Creates a specific page for install instructions, to specifically call out the different options for macOS and Windows.
=> update: clearer OS install instructions

docs/guides/debugging-onesdk.mdx, docs/introduction/getting-started.mdx, docs/introduction/quick-start-sdk.mdx
With new beta (will be released today Aug 14th) of OneSDK switch to see user relevant logs changed. Now there is just on/off, no actual levels.
=> Simplified switch for logs relevant for OneSDK consumer

docs/examples/nodejs.mdx, docs/introduction/getting-started.mdx, docs/introduction/quick-start-sdk.mdx
Updates Node.js run examples to include that you don't need to use the WASI flag with later versions of Node.js
=> update: highlight WASI flag not needed depending on Node version

.github/algolia/config.json
Updates the Algolia config to add stop URLs that include `/classic` so we don't index the old documentation anymore.
=> chore: update Algolia config

docs/examples/cloudflare-workers.mdx
Updates import of OneClient.
Node.js was wrong, but the change will make it right 😉 
Cloudflare Worker will have different package.
=> Update import for Cloudflare Worker

docs/api-examples/pagerduty.mdx
This PR fixes invalid (it does not lead to raw oas) url to PagerDuty docs
=> fix: docs url

docusaurus.config.js
- Removes links to Classic Docs as a start of deprecation of old elements
=> remove links to classic docs
